on:
  push

name: Test Find Issue Key

jobs:
  test-find-issue-key:
    name: Find Issue Key
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Find Issue Key
      id: find
      uses: ./

    - name: Find issue info
      run: echo "Issue ${{ steps.find.outputs.issue }} was found"